version: "3.7"

# Docs:
#   - versioning: https://docs.docker.com/compose/compose-file/compose-versioning/
#   - compose file reference: https://docs.docker.com/compose/compose-file/

# Articles:
#   - Some examples: https://blog.codeship.com/using-docker-compose-for-python-development/
#   - About ".dockerignore" and "Best practices": https://dev.to/djangostars/what-is-docker-and-how-to-use-it-with-python-tutorial-87a

services:


  #############################################################################
  #
  # `truedoc-app` (works under db 'truedoc' with login 'truedoc' in MySQL)
  #
  #############################################################################

  truedoc-app:  # Hostname inside containers: "truedoc-app". Access from local: "http://truedoc-app.localhost:36456".
    ports:
      - "127.0.0.1:36456:5000"
    build:
      context: .

    volumes:  # ATTENTION: you cannot mount a host directory from within the Dockerfile (see: https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes)
      - "./truedoc:/var/lib/truedoc/truedoc"
      - "./upload:/upload"

    depends_on:
      - truedoc-mysql
      - truedoc-pma  # ATTENTION: do NOT use in production.
      - truedoc-rabbitmq


  #############################################################################
  #
  # `truedoc-celery-worker` (queue worker)
  #
  #############################################################################

  truedoc-celery-worker:  # Hostname inside containers: "truedoc-celery-worker".
    image: truedoc_truedoc-app
    volumes:
      - "./truedoc:/var/lib/truedoc/truedoc"
      - "./upload:/upload"

    depends_on:
      - truedoc-app
      - truedoc-rabbitmq

    command: celery -A truedoc.tasks worker -l info


  #############################################################################
  #
  # `truedoc-mysql` (allows 'root' account from any hosts)
  #
  #############################################################################

  truedoc-mysql:  # Hostname inside containers: "truedoc-mysql".
    image: mysql/mysql-server:8.0.18  # https://hub.docker.com/r/mysql/mysql-server/
    ports:
      - "127.0.0.1:3306:3306"
    environment:  # More environment vars: https://dev.mysql.com/doc/refman/8.0/en/docker-mysql-more-topics.html
      MYSQL_DATABASE: truedoc
      MYSQL_PASSWORD: truedoc
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: truedoc
      MYSQL_USER: truedoc
    volumes:
      - "./mysql-data:/var/lib/mysql"
    command:
      ## Required to prevent issue for PMA: "The server requested authentication method unknown to the client [caching_sha2_password]".
      ## TODO: drop after PMA will ready to use PHP compatible version supporting "caching_sha2_password". See: https://github.com/phpmyadmin/phpmyadmin/issues/14220
      - "--default-authentication-plugin=mysql_native_password"


  #############################################################################
  #
  # `truedoc-pma` (works under 'root' in MySQL)
  #
  # Latest versions: https://www.phpmyadmin.net/downloads/
  #
  #############################################################################

  truedoc-pma:  # Hostname inside containers: "truedoc-pma". Access from local: "http://truedoc-pma.localhost:8080".
    image: phpmyadmin/phpmyadmin:4.9  # https://hub.docker.com/r/phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: truedoc-mysql
      PMA_USER: root
      PMA_PASSWORD: truedoc
    depends_on:
      - truedoc-mysql


  #############################################################################
  #
  # `truedoc-nginx` (listening truedoc-nginx:80 for all hosts)
  #
  # Latest versions: https://nginx.org/en/download.html
  #
  #############################################################################

  truedoc-nginx:
    image: nginx:1.16.1-alpine  # https://hub.docker.com/_/nginx
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - "./nginx-dev/conf.d:/etc/nginx/conf.d"
    depends_on:
      - truedoc-app     # Required because nginx has 'truedoc-app' in proxy_pass directive.
      - truedoc-jenkins # Required because nginx has 'truedoc-jenkins' in proxy_pass directive.
      - truedoc-pma     # Required because nginx has 'truedoc-pma' in proxy_pass directive.
      - truedoc-ui      # Required because nginx has 'truedoc-ui' in proxy_pass directive.


  #############################################################################
  #
  # `truedoc-ui`
  #
  #############################################################################

  truedoc-ui:
    image: python:3.7.4-alpine3.10  # https://hub.docker.com/_/python
    working_dir: /var/lib/truedoc-ui  # Just to run `shell` with start point with this directory
    tty: true  # Required to see logs redirected to STDOUT & STDERR by 'docker-compose ... logs truedoc-ui'
    volumes:
      - "./truedoc-ui:/var/lib/truedoc-ui:ro"
    command: python -m http.server --directory /var/lib/truedoc-ui/ 80


  #############################################################################
  #
  # `truedoc-rabbitmq` (UI is available on 'truedoc-rabbitmq-ui.localhost')
  #
  # Latest version: https://www.rabbitmq.com/download.html
  #
  #############################################################################

  truedoc-rabbitmq:
    image: rabbitmq:3.7.20-management-alpine  # https://hub.docker.com/_/rabbitmq
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  #############################################################################
  #
  # `truedoc-jenkins` (UI is available on 'truedoc-jenkins.localhost')
  #
  # Latest versions: https://jenkins.io/download/
  #
  #############################################################################

  truedoc-jenkins:
    image: jenkins/jenkins:lts-alpine  # https://hub.docker.com/r/jenkins/jenkins
    volumes:
      - "./jenkins-data:/var/jenkins_home"
