"""Init DB

Revision ID: 04a0538d15f3
Revises:
Create Date: 2019-12-18 20:36:27.645357+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a0538d15f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('profile_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('pk_profile')),
    sa.UniqueConstraint('email', name=op.f('uq_profile_email'))
    )
    op.create_table('document',
    sa.Column('document_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('profile_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=256), nullable=False),
    sa.Column('filesize', sa.INTEGER(), nullable=False),
    sa.Column('digest', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], name=op.f('fk_document_profile_id_profile')),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_document'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('profile')
    # ### end Alembic commands ###
