"""Add bookmytime entities

Revision ID: f6dafbdb64bf
Revises: 37394f735b32
Create Date: 2019-12-16 18:33:57.051706+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6dafbdb64bf'
down_revision = '37394f735b32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day',
    sa.Column('day_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('profile_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ),
    sa.PrimaryKeyConstraint('day_id')
    )
    op.create_table('slot',
    sa.Column('slot_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('day_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('appointment_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.day_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('slot_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.slot_id'], ),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.alter_column('document', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_table('appointment')
    op.drop_table('slot')
    op.drop_table('day')
    # ### end Alembic commands ###
