"""Init DB with naming convention

Revision ID: cc3f2e17ea9b
Revises: 
Create Date: 2019-12-17 13:00:44.131339+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3f2e17ea9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('profile_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('profile_id', name=op.f('pk_profile')),
    sa.UniqueConstraint('email', name=op.f('uq_profile_email'))
    )
    op.create_table('day',
    sa.Column('day_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('profile_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], name=op.f('fk_day_profile_id_profile')),
    sa.PrimaryKeyConstraint('day_id', name=op.f('pk_day')),
    sa.UniqueConstraint('profile_id', 'date', name=op.f('uq_day_profile_id'))
    )
    op.create_table('document',
    sa.Column('document_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('profile_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('filename', sa.VARCHAR(length=256), nullable=False),
    sa.Column('filesize', sa.INTEGER(), nullable=False),
    sa.Column('digest', sa.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], name=op.f('fk_document_profile_id_profile')),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_document'))
    )
    op.create_table('slot',
    sa.Column('slot_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('day_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('time', sa.TIME(), nullable=False),
    sa.Column('appointment_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['day_id'], ['day.day_id'], name=op.f('fk_slot_day_id_day')),
    sa.PrimaryKeyConstraint('slot_id', name=op.f('pk_slot'))
    )
    op.create_table('appointment',
    sa.Column('appointment_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('slot_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['slot.slot_id'], name=op.f('fk_appointment_slot_id_slot')),
    sa.PrimaryKeyConstraint('appointment_id', name=op.f('pk_appointment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('slot')
    op.drop_table('document')
    op.drop_table('day')
    op.drop_table('profile')
    # ### end Alembic commands ###
