"""Add account for development

Revision ID: 9456d1c4d54b
Revises: bb853ab25f96
Create Date: 2020-05-09 20:03:16.294945+00:00

"""
import truedoc.config
from truedoc.db import db

# revision identifiers, used by Alembic.
revision = '9456d1c4d54b'
down_revision = 'bb853ab25f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if truedoc.config.IS_DEVELOPMENT:
        profile = db.models.Profile(email=truedoc.config.DEVELOPMENT.EMAIL)
        profile.set_password(truedoc.config.DEVELOPMENT.PASSWORD)
        profile.profile_id = truedoc.config.DEVELOPMENT.PROFILE_ID  # TODO: think about add method 'set_id' to Profile class

        db.Profile.create(profile)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if truedoc.config.IS_DEVELOPMENT:
        profile = db.Profile.load(truedoc.config.DEVELOPMENT.PROFILE_ID)
        db.Profile.delete(profile)
    # ### end Alembic commands ###
