"""Change document hash

Revision ID: bb853ab25f96
Revises: 04a0538d15f3
Create Date: 2020-04-26 17:59:22.455074+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb853ab25f96'
down_revision = '04a0538d15f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'digest',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'digest',
               existing_type=sa.VARCHAR(length=128),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
