# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


# Некорректный JSON.
# Должен возвращать: 400 (Bad request).
POST http://truedoc-app.localhost/profile/
Content-Type: application/json

INCORRECT_JSON

###

# Профиль: создание профиля.
# Должен возвращать: 200 (OK) либо ошибку 409 (Conflict) в случае если профиль уже создан.
POST http://truedoc-app.localhost/profile/
Content-Type: application/json

{
  "email": "hello@example.com",
  "password": "password"
}

###

# Профиль: создание профиля, без необходимых полей (пароль, поле 'password').
# Должен возвращать ошибку: 406 (Not Acceptable).
POST http://truedoc-app.localhost/profile/
Content-Type: application/json

{
  "email": "hello@example.com"
}

###

# Профиль: создание профиля, с некорректным email адресом.
# Должен возвращать ошибку: 406 (Not Acceptable).
POST http://truedoc-app.localhost/profile/
Content-Type: application/json

{
  "email": "invalid_email",
  "password": "password"
}

###
